baseURL = "/"
languageCode = "en-us"
title = "Citizen Labs"
theme = "kube"
description = "Empowering citizens to improve their communities and local government."
defaultKeywords = ["citizen labs", "open data", "grand rapids", "open source"]
Paginate = 4

[Params]
  RSSLink = "/index.xml"
  author = "Citizen Labs" # add your company name

  github = "https://github.com/citizenlabsgr" # add your github profile name
  twitter = "" # add your twitter profile
  email = "hello@citizenlabs.org"
  meetup = "https://www.meetup.com/Citizen-Labs/"
  slack = "http://slackin-citizenlabs.herokuapp.com/"
  facebook = "https://www.facebook.com/citizenlabs"



# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-115392197-1"


[menu]

# Main menu

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    name = "Our Work"
    url  = "/our_work/"
    weight = 2

[[menu.main]]
    name = "Get Involved"
    url  = "/get_involved/"
    weight = 3

[[menu.main]]
    name = "News & Events"
    url  = "/news_events/"
    weight = 4

[[menu.main]]
    name = "About"
    identifier = "about"
    url  = "/about/"
    weight = 5

[[menu.main]]
    name = "Contact"
    url  = "/contact/"
    weight = 6
