title = "Citizen Labs"
baseURL = "https://citienlabs.org"
languageCode = "en-us"
theme = "ananke"
themesDir = "../.."

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "UA-115392197-1"
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "/img/favicon/favicon"
  description = "Empowering citizens to improve their communities and local government."
  defaultKeywords = ["citizen labs", "open data", "grand rapids", "open source"]
  github = "https://github.com/citizenlabsgr" # add your github profile name
  twitter = "https://twitter.com/citizen_labs" # add your twitter profile
  email = "hello@citizenlabs.org"
  meetup = "https://www.meetup.com/Citizen-Labs/"
  slack = "http://slackin-citizenlabs.herokuapp.com/"
  facebook = "https://www.facebook.com/citizenlabs"
  instagram = ""
  youtube = ""
  linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "static/images/light-festival.jpg"
  recent_posts_number = 2
